import Image from "next/image";

export default function HomeSubscribe() {
  return (
    <section className="mx-auto mb-24 overflow-hidden">
      <div className="mx-auto">
        <div className="container flex gap-14 justify-center animate-marquee mb-5 ">
          <Image
            className=""
            src={"/graphic.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/salva.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/golden.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/furnitur.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/travel.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/graphic.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/salva.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/golden.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/furnitur.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/travel.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/graphic.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/salva.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/golden.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/furnitur.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/travel.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/graphic.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/salva.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/golden.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/furnitur.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
          <Image
            className=""
            src={"/travel.png"}
            height={70}
            width={200}
            alt=""
          ></Image>
        </div>
      </div>

      <div className="container mx-auto ">
        <div className="flex flex-col w-[1320px] mx-auto">
          <p className="transform -rotate-90 translate-y-[650px] origin-bottom-left text-[40px] my-5">
            Explore new and popular styles
          </p>
          <div className="w-[1320px] h-[648px] flex justify-center gap-6">
            <Image
              className=""
              src={"/card.png"}
              height={648}
              width={648}
              alt=""
            ></Image>

            <div className="flex flex-wrap gap-6">
              <Image
                className=""
                src={"/kategori.png"}
                height={312}
                width={312}
                alt=""
              ></Image>
              <Image
                className=""
                src={"/category-1.png"}
                height={312}
                width={312}
                alt=""
              ></Image>
              <Image
                className=""
                src={"/category-2.png"}
                height={312}
                width={312}
                alt=""
              ></Image>
              <Image
                className=""
                src={"/category-3.png"}
                height={312}
                width={312}
                alt=""
              ></Image>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
